blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
  - name: "Microsoft Security Response Center (MSRC)"
    url: https://msrc.microsoft.com/create-report
    about: Report security bugs